// Code generated by "stringer -type=Note -output=note_string.go"; DO NOT EDIT.

package midi

import "fmt"

const _Note_name = "Cminus2Dbminus2Dminus2Ebminus2Eminus2Fminus2Gbminus2Gminus2Abminus2Aminus2Bbminus2Bminus2Cminus1Dbminus1Dminus1Ebminus1Eminus1Fminus1Gbminus1Gminus1Abminus1Aminus1Bbminus1Bminus1C0Db0D0Eb0E0F0Gb0G0Ab0A0Bb0B0C1Db1D1Eb1E1F1Gb1G1Ab1A1Bb1B1C2Db2D2Eb2E2F2Gb2G2Ab2A2Bb2B2C3Db3D3Eb3E3F3Gb3G3Ab3A3Bb3B3C4Db4D4Eb4E4F4Gb4G4Ab4A4Bb4B4C5Db5D5Eb5E5F5Gb5G5Ab5A5Bb5B5C6Db6D6Eb6E6F6Gb6G6Ab6A6Bb6B6C7Db7D7Eb7E7F7Gb7G7Ab7A7Bb7B7C8Db8D8Eb8E8F8Gb8G8"

var _Note_index = [...]uint16{0, 7, 15, 22, 30, 37, 44, 52, 59, 67, 74, 82, 89, 96, 104, 111, 119, 126, 133, 141, 148, 156, 163, 171, 178, 180, 183, 185, 188, 190, 192, 195, 197, 200, 202, 205, 207, 209, 212, 214, 217, 219, 221, 224, 226, 229, 231, 234, 236, 238, 241, 243, 246, 248, 250, 253, 255, 258, 260, 263, 265, 267, 270, 272, 275, 277, 279, 282, 284, 287, 289, 292, 294, 296, 299, 301, 304, 306, 308, 311, 313, 316, 318, 321, 323, 325, 328, 330, 333, 335, 337, 340, 342, 345, 347, 350, 352, 354, 357, 359, 362, 364, 366, 369, 371, 374, 376, 379, 381, 383, 386, 388, 391, 393, 395, 398, 400, 403, 405, 408, 410, 412, 415, 417, 420, 422, 424, 427, 429}

func (i Note) String() string {
	if i >= Note(len(_Note_index)-1) {
		return fmt.Sprintf("Note(%d)", i)
	}
	return _Note_name[_Note_index[i]:_Note_index[i+1]]
}
