// Code generated by "stringer -type=Rhythm -output=rhythm_string.go"; DO NOT EDIT.

package midi

import "fmt"

const (
	_Rhythm_name_0 = "AcousticBassDrumBassDrum1SideStickAcousticSnareHandClap"
	_Rhythm_name_1 = "ElectricSnareLowFloorTomClosedHiHatHighFloorTomPedalHiHatLowTomOpenHiHatLowMidTomHiMidTomCrashCymbal1"
	_Rhythm_name_2 = "HighTomRideCymbal1ChineseCymbalRideBellTambourineSplashCymbalCowbellCrashCymbal2VibraslapRideCymbal2"
	_Rhythm_name_3 = "HiBongoLowBongoMuteHiCongaOpenHiCongaLowCongaHighTimbaleLowTimbaleHighAgogoLowAgogoCabasa"
	_Rhythm_name_4 = "MaracasShortWhistleLongWhistleShortGuiroLongGuiroClavesHiWoodBlockLowWoodBlockMuteCuicaOpenCuica"
	_Rhythm_name_5 = "MuteTriangleOpenTriangle"
)

var (
	_Rhythm_index_0 = [...]uint8{0, 16, 25, 34, 47, 55}
	_Rhythm_index_1 = [...]uint8{0, 13, 24, 35, 47, 57, 63, 72, 81, 89, 101}
	_Rhythm_index_2 = [...]uint8{0, 7, 18, 31, 39, 49, 61, 68, 80, 89, 100}
	_Rhythm_index_3 = [...]uint8{0, 7, 15, 26, 37, 45, 56, 66, 75, 83, 89}
	_Rhythm_index_4 = [...]uint8{0, 7, 19, 30, 40, 49, 55, 66, 78, 87, 96}
	_Rhythm_index_5 = [...]uint8{0, 12, 24}
)

func (i Rhythm) String() string {
	switch {
	case 53 <= i && i <= 57:
		i -= 53
		return _Rhythm_name_0[_Rhythm_index_0[i]:_Rhythm_index_0[i+1]]
	case 64 <= i && i <= 73:
		i -= 64
		return _Rhythm_name_1[_Rhythm_index_1[i]:_Rhythm_index_1[i+1]]
	case 80 <= i && i <= 89:
		i -= 80
		return _Rhythm_name_2[_Rhythm_index_2[i]:_Rhythm_index_2[i+1]]
	case 96 <= i && i <= 105:
		i -= 96
		return _Rhythm_name_3[_Rhythm_index_3[i]:_Rhythm_index_3[i+1]]
	case 112 <= i && i <= 121:
		i -= 112
		return _Rhythm_name_4[_Rhythm_index_4[i]:_Rhythm_index_4[i+1]]
	case 128 <= i && i <= 129:
		i -= 128
		return _Rhythm_name_5[_Rhythm_index_5[i]:_Rhythm_index_5[i+1]]
	default:
		return fmt.Sprintf("Rhythm(%d)", i)
	}
}
